### ISSUE TITLE
Support ghc 7.10.x

### ISSUE THREAD

**Issue by PierreR** [jfeltz/dash-haskell#11]
Would it be hard to support ghc-7.10.x ?

Cheers

**Comment by PierreR** [comment]
Well I can see it is not straightforward ... The haddock for the GHC module is missing on hackage ... Is there a place where I can get generated docset for common packages ?

**Comment by jfeltz** [comment]
It's in the works.

**Comment by PierreR** [comment]
I had a go with it but the GHC API has changed quite a bit in 7.10 so I gave up.

Waiting for the feature release seems quite reasonable ;-)

**Comment by jfeltz** [comment]
fixed with merge of https://github.com/jfeltz/dash-haskell/pull/12 onto master
